modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GPLv3"

[[mods]]
modId="enchantedcharms"
version="${file.jarVersion}"
displayName="Enchanted Charms"
logoFile="enchantedcharms.png"
credits="BrokenKeyboard"
authors="BrokenKeyboard"
description='''This mod adds equippable charms with different abilities to Minecraft.'''

[[dependencies.enchantedcharms]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.enchantedcharms]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.enchantedcharms]]
    modId="curios"
    mandatory=true
    versionRange="${curios_version}"
    ordering="NONE"
    side="BOTH"